# Homebrew formula for wardn.
#
# This is generated by scripts/update-homebrew-formula.sh from the latest
# published GitHub release — do not hand-edit the url/sha256 fields, re-run
# that script after cutting a new release instead.
#
# To use locally before a tap is published: `brew install --build-from-source
# ./Formula/wardn.rb` won't work for a binary formula; instead:
#   brew tap-new rohansx/wardn        # one-time, creates a local tap repo
#   cp Formula/wardn.rb $(brew --repository rohansx/wardn)/Formula/
#   brew install rohansx/wardn/wardn
#
# Publishing an actual `rohansx/homebrew-wardn` tap repo (or submitting to
# homebrew-core) is a manual step requiring repo creation/maintainer review
# — not something this script does.
class Wardn < Formula
  desc "Credential-isolation proxy for AI coding agents"
  homepage "https://github.com/rohansx/wardn"
  version "0.4.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/rohansx/wardn/releases/download/v0.4.1/wardn-darwin-arm64.tar.gz"
      sha256 "823dc1fda2db939f9bce7b70ba59d013ba2ab12962f8b9c308fdb0eb9b13d47c"
    end
    on_intel do
      url "https://github.com/rohansx/wardn/releases/download/v0.4.1/wardn-darwin-amd64.tar.gz"
      sha256 "06b5d9534cedfe2f74aa8aa6c80564db6ce39ee78b0e13a2b57e213ebabc0e4f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/rohansx/wardn/releases/download/v0.4.1/wardn-linux-arm64.tar.gz"
      sha256 "f498087a5ce0aee4f1b1a931d66dbf8672ebfac749a95e2c7b375459fa45678d"
    end
    on_intel do
      url "https://github.com/rohansx/wardn/releases/download/v0.4.1/wardn-linux-amd64.tar.gz"
      sha256 "3359653abcc8461e7cbe33c7e45f7590d1d4b609a516cd94ba7694359351a3cc"
    end
  end

  def install
    bin.install "wardn"
  end

  test do
    system "#{bin}/wardn", "--version"
  end
end
