#!/bin/sh
# Regenerate Formula/wardn.rb from a published GitHub release's tarballs and
# .sha256 checksum files (uploaded by .github/workflows/release.yml).
#
# Usage: ./scripts/update-homebrew-formula.sh [version]
#   version defaults to the latest GitHub release tag if omitted, e.g. v0.5.0.
#
# Requires: gh (authenticated), awk.
set -e

REPO="rohansx/wardn"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
FORMULA_PATH="${SCRIPT_DIR}/../Formula/wardn.rb"

VERSION="${1:-$(gh release view --repo "$REPO" --json tagName -q .tagName)}"
if [ -z "$VERSION" ]; then
    echo "error: could not determine a release version (pass one explicitly)" >&2
    exit 1
fi
VERSION_NUM="${VERSION#v}"

fetch_sha() {
    artifact="$1"
    gh release download "$VERSION" --repo "$REPO" -p "${artifact}.sha256" -O - | awk '{print $1}'
}

echo "fetching checksums for ${VERSION}..."
DARWIN_ARM64_SHA="$(fetch_sha wardn-darwin-arm64.tar.gz)"
DARWIN_AMD64_SHA="$(fetch_sha wardn-darwin-amd64.tar.gz)"
LINUX_ARM64_SHA="$(fetch_sha wardn-linux-arm64.tar.gz)"
LINUX_AMD64_SHA="$(fetch_sha wardn-linux-amd64.tar.gz)"

for sha in "$DARWIN_ARM64_SHA" "$DARWIN_AMD64_SHA" "$LINUX_ARM64_SHA" "$LINUX_AMD64_SHA"; do
    if [ -z "$sha" ]; then
        echo "error: failed to fetch one or more checksums for ${VERSION}" >&2
        exit 1
    fi
done

cat > "$FORMULA_PATH" <<EOF
# Homebrew formula for wardn.
#
# This is generated by scripts/update-homebrew-formula.sh from the latest
# published GitHub release — do not hand-edit the url/sha256 fields, re-run
# that script after cutting a new release instead.
#
# To use locally before a tap is published: \`brew install --build-from-source
# ./Formula/wardn.rb\` won't work for a binary formula; instead:
#   brew tap-new rohansx/wardn        # one-time, creates a local tap repo
#   cp Formula/wardn.rb \$(brew --repository rohansx/wardn)/Formula/
#   brew install rohansx/wardn/wardn
#
# Publishing an actual \`rohansx/homebrew-wardn\` tap repo (or submitting to
# homebrew-core) is a manual step requiring repo creation/maintainer review
# — not something this script does.
class Wardn < Formula
  desc "Credential-isolation proxy for AI coding agents"
  homepage "https://github.com/${REPO}"
  version "${VERSION_NUM}"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/${REPO}/releases/download/${VERSION}/wardn-darwin-arm64.tar.gz"
      sha256 "${DARWIN_ARM64_SHA}"
    end
    on_intel do
      url "https://github.com/${REPO}/releases/download/${VERSION}/wardn-darwin-amd64.tar.gz"
      sha256 "${DARWIN_AMD64_SHA}"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/${REPO}/releases/download/${VERSION}/wardn-linux-arm64.tar.gz"
      sha256 "${LINUX_ARM64_SHA}"
    end
    on_intel do
      url "https://github.com/${REPO}/releases/download/${VERSION}/wardn-linux-amd64.tar.gz"
      sha256 "${LINUX_AMD64_SHA}"
    end
  end

  def install
    bin.install "wardn"
  end

  test do
    system "#{bin}/wardn", "--version"
  end
end
EOF

echo "wrote ${FORMULA_PATH} for ${VERSION}"
